### ISSUE TITLE
Self Calibration p8 value

### ISSUE THREAD

**Issue by mtbdeligt** [adafruit/Adafruit_Python_BMP#14]
works on my piA+ but pressure values are a bit off. Checked the self.cal_p8 value in the datasheet which shows -14600 rather than the -14500 value in the code.

**Comment by ladyada** [comment]
hey sorry, where is "cal_p8"? i dont see it?

**Comment by mtbdeligt** [comment]
Line 94 - self.cal_p8 it is a value from the data sheet and not one of the
values from the unit itself.

**Comment by mtbdeligt** [comment]
apologies, this is an issue against the pull request for the BMP280 not the main Adafruit_Python_BMP
