### ISSUE TITLE
BMP085 ERROR AFTER UPDATING RASPBIAN AND KERNEL

### ISSUE THREAD

**Issue by perrycannon** [adafruit/Adafruit_Python_BMP#20]
- Raspberry Pi with Raspbian operating system, updated today (apt-get update, apt-get dIst-upgrade) with latest kernel (sudo rpi-update).
  
- Python version 2.7.

- Error message you are receiving:
Traceback (most recent call last):
  File "simpletest.py", line 37, in <module>
    sensor = BMP085.BMP085()
  File "build/bdist.linux-armv6l/egg/Adafruit_BMP/BMP085.py", line 67, in __init__
  File "build/bdist.linux-armv6l/egg/Adafruit_GPIO/I2C.py", line 63, in get_i2c_device
  File "build/bdist.linux-armv6l/egg/Adafruit_GPIO/I2C.py", line 55, in get_default_bus
RuntimeError: Could not determine default I2C bus for platform.

- My python program was working prior to updating my Raspberry Pi B. After updating received the above error. The above error was received using the simpletest.py example. Also received with my python script. i2cdetect displays the address of the BMP085.

pi@raspberrypiLights:~/Adafruit_Python_BMP/examples $ i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- 3c -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- UU -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- 77                         

Fixed myself. Installed Adafruit Python GPIO Library.

**Comment by patricktokeeffe** [comment]
As mentioned in #18, this can be resolved by specifying a `busnum`. For a Pi Model B+, this works:
```
import Adafruit_BMP.BMP085 as BMP
sensor = BMP.BMP085(busnum=1)
```
