### ISSUE TITLE
IOError: [Errno 110] Connection timed out

### ISSUE THREAD

**Issue by lrusak** [adafruit/Adafruit_Python_BMP#4]
Using the simpletest.py I get constant errors

```
python simpletest.py 
Traceback (most recent call last):
  File "simpletest.py", line 37, in <module>
    sensor = BMP085.BMP085()
  File "/usr/lib/python2.7/site-packages/Adafruit_BMP/BMP085.py", line 68, in __init__
    self._load_calibration()
  File "/usr/lib/python2.7/site-packages/Adafruit_BMP/BMP085.py", line 72, in _load_calibration
    self.cal_AC2 = self._device.readS16BE(BMP085_CAL_AC2)   # INT16
  File "/usr/lib/python2.7/site-packages/Adafruit_GPIO/I2C.py", line 195, in readS16BE
    return self.readS16(register, little_endian=False)
  File "/usr/lib/python2.7/site-packages/Adafruit_GPIO/I2C.py", line 172, in readS16
    result = self.readU16(register, little_endian)
  File "/usr/lib/python2.7/site-packages/Adafruit_GPIO/I2C.py", line 159, in readU16
    result = self._bus.read_word_data(self._address,register) & 0xFFFF
IOError: [Errno 110] Connection timed out
```

I'm not sure what is causing this. I have one other sensor on the i2c bus.

```
i2cdetect -y 0
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: 60 -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- 77  
```

The only way I can get it to show me anything is if I do something like

```
value = None
while value is None:
  try:
    value = BMP085.BMP085().read_pressure()
    print 'Pressure = {0:0.2f} Pa'.format(value)
  except:
    pass
```

Even then I seem to get wild values

```
Pressure = 1092309.00 Pa
```

So I'm not sure if my sensor is buggered, or if the voltage is dropping too much on the 3.3v line to run both sensors (the other sensor is an si1145). The si1145 seems to have the same error and needs a similar solution when I use it.

So it's either the voltage, or something related to daisy chaining the two sensors on the same i2c bus

EDIT: 
Just did some more testing, ran the simpletest.py in a loop and monitored the voltage, it was a constant 3.34v, so that's fine.
I also tried each sensor on it's own, and it still had the timeout issue. So now I think it must be related to my RPi or my kernel config.

**Comment by tdicola** [comment]
Hrm that's odd, one thing I'm curious about are you using a Pi 2 or original Pi?  I've seen a similar intermittent error with a different I2C device on the Pi 2 and am curious if you're seeing something similar here too.

**Comment by lrusak** [comment]
I'm using an original first revision RPi B.

After more digging it seems to be an issue in the kernel.
https://github.com/raspberrypi/linux/issues/865

I'll try rebuilding with the latest kernel or try using an older kernel if that doesn't work.
currently I'm using 3.19.0 and I have the following line in config.txt
```
dtparam=i2c_arm=on
```

Will report back after I test some different kernels.

**Comment by tdicola** [comment]
Ouch, thanks for linking to that bug--that's somewhat annoying to see the issue at the kernel level.  If it helps, you might try the stock Raspbian release that's on the 3.18 kernel: http://www.raspberrypi.org/downloads/  Good to know that 3.19 might have some issues right now.

**Comment by jeanleflambeur** [comment]
This seems to be a different issue than the one in the linked issue. You are getting a "transfer setup timed out" while issue #865 is about "transfer timed out".  Can you detail a bit your setup pls?
- Do you have a Pi camera attached?
- What i2c baud are you using?
- Combined transactions on? (you can just paste the kernel params from cmdline.txt here)
- Overclocked Pi?
- Do other sensors work?
- Did you try an older kernel ( < 0ca4c1f57c84bb114641176d63d16ce345f5a95d)?
- When you get bad readings do you have a simultaneous timeout in dmesg?

**Comment by beheh** [comment]
I'm seeing the same issue with a different sensor (MPL3115A2), so I believe it is a module problem. In case it helps, my setup (running `Linux raspberrypi 3.18.7-v7+ #755 SMP PREEMPT Thu Feb 12 17:20:48 GMT 2015 armv7l GNU/Linux`):

* No camera attached
* Tried 100000, 32000, 5000 with the same error everytime.
* Yes, since the sensor requires it
* No
* Only one sensor to test with right now
* Running 3.18
* Yes: `[ 1923.121754] i2c i2c-1: transfer setup timed out`

**Comment by javiisanchez** [comment]
Hi,
I'm seeing the same issue, first the sensor did a good reading, after I put a while to see continuosly the data and the exception appeared (after half minut), and now the sensor wasn't connected to the I2C bus. (with the comand i2cdetect -y 1 I don't see any sensor, that before, I've saw. 
Can you help me?

**Comment by ladyada** [comment]
hiya we're closing these issues and archiving this repo because this library has been deprecated!

the bmp085 and bmp180 are no longer made, and are replaced by the bmp280 + friends

we are now only using our circuitpython sensor libraries in python

check out this guide for using the bmp280 with python!
https://learn.adafruit.com/adafruit-bmp280-barometric-pressure-plus-temperature-sensor-breakout
