### ISSUE TITLE
Doesn't work with Python 3.4

### ISSUE THREAD

**Issue by loanlaux** [adafruit/Adafruit_Python_BMP#7]
I tried using this library in both Python 2 and 3 with a BMP180 sensor from Adafruit. It works great with version 2.7.x, but I'm having 'unsupported operand type(s)' errors when trying to use this library with Python 3.4:

![screen shot 2015-06-02 at 15 24 01](https://cloud.githubusercontent.com/assets/2156504/7936695/6f232004-093b-11e5-8c74-cbdcc631e391.png)

Please note that the sensor seems to be recognized, as shows the following screenshot:

![screen shot 2015-06-02 at 15 25 08](https://cloud.githubusercontent.com/assets/2156504/7936740/bb66cff6-093b-11e5-9f4f-aa6f1241cdde.png)

I'm working with a Raspberry Pi model B if that helps.

**Comment by tdicola** [comment]
Oh thanks for grabbing the details on the failure--yeah I don't think I've tested this one with Python 3.4 so stick with python 2.7 for now.  I'll try to take a look later this week though to see why the bit shift isn't valid in 3.4.  Thanks!

**Comment by loanlaux** [comment]
Yep, switched my project to Python 2.7 for now. Thank you.

**Comment by anthonyscorrea** [comment]
I believe I found the issue, not sure exactly what the best fix is, though. Definitely a problem with the result of the addition of two ints becoming a float. Then the bitwise operators fail.

Changing it like below definitely fixes the issue. I have been testing with the debugging values, will test again with the actual unit when I get home. (There are three other instances where int addition yields a float)

![image](https://cloud.githubusercontent.com/assets/8305953/10614594/be20c9ba-7720-11e5-8b27-977b182ec32a.png)

Not sure exactly what the best practice fix is, but I will be more than happy to make this change.

**Comment by dinomite** [comment]
@campenberger's fix in pull request #8 fixes this.

**Comment by tdicola** [comment]
Oh this should be resolved now, a few months ago we did a pass adding python 2 and 3 support to all the libs.  Can see more details here: https://github.com/adafruit/Adafruit-Raspberry-Pi-Python-Code  Thanks!
